# Get your APIKey from the MinecraftMarket panel
APIKey: randomstring
# Time between purchases checks in minutes
CheckInterval: 1
# Language to use on messages language files located at langs folder
Lang: en
# Log errors no need to activate this
Debug: false